//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSharpPlus.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DSharpPlus.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DSP0005Title {
            get {
                return ResourceManager.GetString("DSP0005Title", resourceCulture);
            }
        }
        
        internal static string DSP0005Description {
            get {
                return ResourceManager.GetString("DSP0005Description", resourceCulture);
            }
        }
        
        internal static string DSP0005MessageFormat {
            get {
                return ResourceManager.GetString("DSP0005MessageFormat", resourceCulture);
            }
        }
        
        internal static string DSP0006Title {
            get {
                return ResourceManager.GetString("DSP0006Title", resourceCulture);
            }
        }
        
        internal static string DSP0006Description {
            get {
                return ResourceManager.GetString("DSP0006Description", resourceCulture);
            }
        }
        
        internal static string DSP0006MessageFormat {
            get {
                return ResourceManager.GetString("DSP0006MessageFormat", resourceCulture);
            }
        }
        
        internal static string DSP0007Title {
            get {
                return ResourceManager.GetString("DSP0007Title", resourceCulture);
            }
        }
        
        internal static string DSP0007Description {
            get {
                return ResourceManager.GetString("DSP0007Description", resourceCulture);
            }
        }
        
        internal static string DSP0007MessageFormat {
            get {
                return ResourceManager.GetString("DSP0007MessageFormat", resourceCulture);
            }
        }
        
        internal static string DSP1001Title {
            get {
                return ResourceManager.GetString("DSP1001Title", resourceCulture);
            }
        }
        
        internal static string DSP1001Description {
            get {
                return ResourceManager.GetString("DSP1001Description", resourceCulture);
            }
        }
        
        internal static string DSP1001MessageFormat {
            get {
                return ResourceManager.GetString("DSP1001MessageFormat", resourceCulture);
            }
        }
    }
}
