name: "Publish Release"
on:
  release:
    types: ["published"]

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  publish_release:
    name: Publish Release
    runs-on: "ubuntu-latest"
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.103
      - name: Login to NuGet
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Build NuGet packages
        run: "mkdir build && dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg -c Release -o build"
      - name: Publish NuGet packages
        run: "dotnet nuget push \"build/*\" -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json"
      - name: Upload NuGet packages to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: PR NuGet Packages
          path: build/*
      - name: Upload NuGet Packages To Github Release
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.
